### PR TITLE
Oom python3

### PR DESCRIPTION
**Pull request by bacharya**
Hi,

Please review the changes with python3 support along with python2 compatibility.
Please find the attached test log.

Thanks,
Bhishma

[OOM_test_log.txt](https://github.com/opencomputeproject/oom/files/6771044/OOM_test_log.txt)

### CODE REVIEW

**Comment by donboll** [comment]
Hi,

 

Thanks for the comprehensive pull request.  I see lots of good test data, both python and python3.  I note also ‘opticsdump.py’, which looks like a useful addition.

 

I want to take some time to review the actual changes as well as test some myself.  Unfortunately I will be offline for the next two weeks.  So, I am not ignoring you, I just won’t be able to work on this until I’m back online.

 

Don

 

From: bacharya ***@***.*** 
Sent: Tuesday, July 06, 2021 8:18 AM
To: opencomputeproject/oom ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opencomputeproject/oom] Oom python3 (#23)

 

Hi,

Please review the changes with python3 support along with python2 compatibility.
Please find the attached test log.

Thanks,
Bhishma

OOM_test_log.txt <https://github.com/opencomputeproject/oom/files/6771044/OOM_test_log.txt> 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/opencomputeproject/oom/pull/23


Commit Summary


*	Changes related to python3 support
*	Changes related to pylint and pylint3 score.


File Changes


*	M apps/inventory.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-42f1fb1c7b9ad25bd157fe34ead469009fa94fe01db18fa795cadea7d8e7193c>  (12) 
*	M apps/iop.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-2033ea4d14ebd710352475b1c94b198ad43200e3e365002e955a37f07cea2d69>  (58) 
*	M apps/ocpdemo.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-c341040a2704b8209c8a90833ca5173ee3333309ba8b68084d91a9ee27071348>  (10) 
*	M apps/oomdemo.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-46c3405155dfba67ad47780623ff5344a77bb21b2cce9fad7ebf28ec3b7cca7d>  (100) 
*	M apps/oomjsonsvr.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-e44158bceadb91976a859f24c6718a7ce261727febac9c87abc0a0b55b4d9170>  (4) 
*	M apps/oomwrite.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-e7b92fe6f1d4ab0b9cbd09d426e726324c867826f0bb00b399b77b0c7373c29a>  (64) 
*	M demo/DOMgui.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-35559d1868ab14c3be4a6a1bf0f62a2272c597a01dd5d3aeda1f8a59a670dd03>  (2) 
*	M demo/gui.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-cebc357e1fa35c4c379899dc67c78bf4650c63f9c73548c2e35442b156de6492>  (4) 
*	M oom/decode.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-7d5fd2b948004596ab309e105bcef3b5c3d336485e92e761cbb9a56f141f25d3>  (488) 
*	M oom/oom.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-9a6ad19b740be44dd30a303181afdfac1c3dad7f389189d149f4b2d70924b036>  (5) 
*	M oom/oomjsonshim.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-b2efe818e10a80423f3d80a059d7497fb7e3b8568a5083d6b2e81a16d284c7d0>  (4) 
*	M oom/oomlib.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-7cea0fa55f0d8a73fb41017eb96e3c40ceeac49d3d2d798656be96c04ef28a42>  (42) 
*	M oom/oomsysfsshim.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-5d061fe18b6748acfaa0a853a59f4471cbb20fb662ba7a9df06d680be296da9f>  (160) 
*	M oom/oomtypes.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-90fb2b09c3c79d047faed5743e029e19b82e21537c71c75a1e93125b5266e01a>  (3) 
*	M setup.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7>  (2) 
*	M test/keytest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-020b92c58100628971141b775d81bdc21464b6f4ff9d561f77800b3ec072a812>  (25) 
*	M test/oomtest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-18bafc3710d93f0bd762005dcbff1bfb7c7d2480c218f09da782bfb60db1e990>  (6) 
*	A test/opticsdump.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-5d0ca11289b515a69f52b1f25bb566996e440d4133715b5bb5b970b2f642683e>  (95) 
*	M test/qtest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-bb369d860bcdbe21670163df357529757cbfe843af2aa584df01a90f56a86942>  (33) 


Patch Links:


*	https://github.com/opencomputeproject/oom/pull/23.patch
*	https://github.com/opencomputeproject/oom/pull/23.diff

**Comment by donboll** [comment]
A quick status report on the OOM python3 submittal…

 

I am back from vacation :)

 

I read all of the code changes, they appeared to be good.

 

I notice some new code, including support for a couple of accton platforms in oomsysfsshim.py and a new test case test/opticsdump.py.  I like them both, and will include them when I have a candidate ready to commit.

 

I ran a bunch of tests, and came up with a bunch of issues.  Some are silly, like my python 2.7 interpreter sees ‘print()’ and it actually prints ‘()’.  I’m changing all of the print() to print(“”).  Some of the issues would have been difficult to find without all the test scaffolding I have built.  The CFP code doesn’t work, the JSON server/shim code doesn’t work.  I have developed fixes for them, at least for python 2.7.  (I don’t have a JSON app that works on python3.  When someone does, they/we can debug it.)

 

The encode/decode ‘utf-8’ code doesn’t work quite right.  I’ve fought between ctypes create_string_buffer and every other Python representation of strings and bytes since the origin of OOM.  It continues to plague me.  I found a remarkably simple solution to some of the cases:

 

  c = create_string_buffer(4)

 s = c[:]

 

This works in both P2.7 and P3!  It copies c to s.  In P2.7 s is of type ‘str’, in P3 s is of type ‘class bytes’.  This reduces get_string(x) to just one line: return(x[:])

 

I pulled the pull request into my development environment and find that it has all DOS newlines, rather than Linux newlines in the changed files (and even in some that didn’t change).  I will switch those back so they look like native Linux (even though I actually develop on Cygwin on Windows :)).

 

I seem to have a working set of code that I’m satisfied with, but it is sort of a mess right now.  Having solved all the issues, I’m going to start over, with a clean branch, and methodically apply all of the changes in a way I can review, test and commit.  That will probably take at least a week.

 

I’ll post a candidate for y’all to test when I have it ready.

 

Don

 

 

From: bacharya ***@***.*** 
Sent: Tuesday, July 06, 2021 8:18 AM
To: opencomputeproject/oom ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opencomputeproject/oom] Oom python3 (#23)

 

Hi,

Please review the changes with python3 support along with python2 compatibility.
Please find the attached test log.

Thanks,
Bhishma

OOM_test_log.txt <https://github.com/opencomputeproject/oom/files/6771044/OOM_test_log.txt> 

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/opencomputeproject/oom/pull/23


Commit Summary


*	Changes related to python3 support
*	Changes related to pylint and pylint3 score.


File Changes


*	M apps/inventory.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-42f1fb1c7b9ad25bd157fe34ead469009fa94fe01db18fa795cadea7d8e7193c>  (12) 
*	M apps/iop.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-2033ea4d14ebd710352475b1c94b198ad43200e3e365002e955a37f07cea2d69>  (58) 
*	M apps/ocpdemo.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-c341040a2704b8209c8a90833ca5173ee3333309ba8b68084d91a9ee27071348>  (10) 
*	M apps/oomdemo.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-46c3405155dfba67ad47780623ff5344a77bb21b2cce9fad7ebf28ec3b7cca7d>  (100) 
*	M apps/oomjsonsvr.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-e44158bceadb91976a859f24c6718a7ce261727febac9c87abc0a0b55b4d9170>  (4) 
*	M apps/oomwrite.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-e7b92fe6f1d4ab0b9cbd09d426e726324c867826f0bb00b399b77b0c7373c29a>  (64) 
*	M demo/DOMgui.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-35559d1868ab14c3be4a6a1bf0f62a2272c597a01dd5d3aeda1f8a59a670dd03>  (2) 
*	M demo/gui.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-cebc357e1fa35c4c379899dc67c78bf4650c63f9c73548c2e35442b156de6492>  (4) 
*	M oom/decode.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-7d5fd2b948004596ab309e105bcef3b5c3d336485e92e761cbb9a56f141f25d3>  (488) 
*	M oom/oom.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-9a6ad19b740be44dd30a303181afdfac1c3dad7f389189d149f4b2d70924b036>  (5) 
*	M oom/oomjsonshim.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-b2efe818e10a80423f3d80a059d7497fb7e3b8568a5083d6b2e81a16d284c7d0>  (4) 
*	M oom/oomlib.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-7cea0fa55f0d8a73fb41017eb96e3c40ceeac49d3d2d798656be96c04ef28a42>  (42) 
*	M oom/oomsysfsshim.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-5d061fe18b6748acfaa0a853a59f4471cbb20fb662ba7a9df06d680be296da9f>  (160) 
*	M oom/oomtypes.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-90fb2b09c3c79d047faed5743e029e19b82e21537c71c75a1e93125b5266e01a>  (3) 
*	M setup.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7>  (2) 
*	M test/keytest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-020b92c58100628971141b775d81bdc21464b6f4ff9d561f77800b3ec072a812>  (25) 
*	M test/oomtest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-18bafc3710d93f0bd762005dcbff1bfb7c7d2480c218f09da782bfb60db1e990>  (6) 
*	A test/opticsdump.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-5d0ca11289b515a69f52b1f25bb566996e440d4133715b5bb5b970b2f642683e>  (95) 
*	M test/qtest.py <https://github.com/opencomputeproject/oom/pull/23/files#diff-bb369d860bcdbe21670163df357529757cbfe843af2aa584df01a90f56a86942>  (33) 


Patch Links:


*	https://github.com/opencomputeproject/oom/pull/23.patch
*	https://github.com/opencomputeproject/oom/pull/23.diff

**Comment by donboll** [comment]
Re: OOM Python3 support...  I have completed, tested and committed my changes to Bacharya's pull request.  Everything that I tried now works, I'm prepared to commit this to the OOM mainline.

Oddly, I seem to have committed and pushed the changes into bacharya's oom_python3 branch.  Not sure how I did that, but  I did, which means that interested parties can access the changes from the pull request #23 page.  Look for 'donboll added 2 commits...', the final one is 256731e.

I'd like a confirmation from bacharya and Mikhail that this version works before merging into master.  If I don't get a response, I'll probably go ahead and commit late next week (~August 11).

Don

**Comment by bacharya** [comment]
Hi Don,

I have validated your changes in my setup and the test results look perfectly fine. Hereby I acknowledge my confirmation.

In addition, I have made minor enhancements in keytest.py and qtest.py. Please consider the changes too(commit-id 701fff3).

Thanks,
Bhishma

**Comment by donboll** [comment]
Excellent enhancements, I almost did the same thing.  Your solution is simple and effective, I like it.

 

Don

**Comment by donboll** [comment]
Done.  OOM now supports Python 3!  Thank you bacharya.  Latest code is available in the OOM github repo.  FYI, optoe.c, the linux driver, has also been substantially updated and supports several kernel subsystems including device tree configuration and nvmem access.  See all the info in oom/optoe/optoe.rst.

 

Don

**Pull request merged**
